version: '3.8'

services:
  # 1. Database Tier
  mongodb:
    image: mongo:6.0
    container_name: local_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Backend Tier
  backend:
    build: ./backend
    container_name: local_backend
    ports:
      - "5001:5000"
    environment:
      # We tell Flask to connect to the 'mongodb' service over Docker's internal DNS network
      - MONGO_URI=mongodb://mongodb:27017/taskdb
    depends_on:
      - mongodb

  # 3. Frontend Tier
  frontend:
    build: ./frontend
    container_name: local_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
